<script setup lang="ts">
import { useData } from 'vitepress'
import { useSidebar } from 'vitepress/dist/client/theme-default/composables/sidebar'
import VPLink from 'vitepress/dist/client/theme-default/components/VPLink.vue';

const { theme } = useData()
const { hasSidebar } = useSidebar()
</script>

<template>
  <footer v-if="theme.footer" class="VPFooter" :class="{ 'has-sidebar': hasSidebar }">
    <div class="container">
      <p v-if="theme.footer.message" class="message" v-html="theme.footer.message"></p>
      <p v-if="theme.footer.hash" class="message">Last updated:
        <VPLink class="footer-link" target="_blank" ref="noreferrer"
          :href="`https://github.com/sshwy/lamcalc/commit/${theme.footer.hash}`">{{
            theme.footer.hash
          }}</VPLink>
      </p>
      <p v-if="theme.footer.vitePressVersion" class="message">Generated by
        <VPLink class="footer-link" target="_blank" ref="noreferrer" href="https://vitepress.dev">VitePress v{{
          theme.footer.vitePressVersion }}</VPLink>
      </p>
      <p v-if="theme.footer.copyright" class="copyright" v-html="theme.footer.copyright"></p>
    </div>
  </footer>
</template>

<style scoped>
.VPFooter {
  position: relative;
  z-index: var(--vp-z-index-footer);
  border-top: 1px solid var(--vp-c-gutter);
  padding: 32px 24px;
  background-color: var(--vp-c-bg);
}

.VPFooter.has-sidebar {
  display: none;
}

@media (min-width: 768px) {
  .VPFooter {
    padding: 32px;
  }
}

.container {
  margin: 0 auto;
  max-width: var(--vp-layout-max-width);
  text-align: center;
}

.message,
.copyright {
  line-height: 24px;
  font-size: 14px;
  font-weight: 500;
  color: var(--vp-c-text-2);
}

.message {
  order: 2;
}

.copyright {
  order: 1;
}

.footer-link {
  transition: color 0.25s;
}

.footer-link:hover {
  color: var(--vp-c-brand);
}
</style>